CREATE TABLE "nazar"
(
   ID TEXT PRIMARY KEY NOT NULL ,
   FOLDER_ID TEXT  ,
   TITLE TEXT  ,
   LOGO TEXT,
   EMAIL TEXT  ,
   PHONE_NUMBER TEXT,
   FAX TEXT,
   OFFICE_PHONE TEXT,
   WEBSITE TEXT,
   NOTES TEXT,
   ENABLED BOOLEAN,
   ADDRESS TEXT,
   EXTRA_ADDRESS TEXT,
   COUNTRY TEXT,
   STATE TEXT,
   CITY TEXT,
   ZIP_CODE TEXT,
   CREATED_AT BIGINT
    );